apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi-api
  namespace: taxi-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taxi-api
  template:
    metadata:
      labels:
        app: taxi-api
    spec:
      containers:
        - name: api
          image: taxi-api:v1.01
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/taxidb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: SPRING_REDIS_HOST
              value: redis