apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi-generator
  namespace: taxi-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taxi-generator
  template:
    metadata:
      labels:
        app: taxi-generator
    spec:
      containers:
        - name: taxi-generator
          image: taxi-generator:v1.01
          imagePullPolicy: IfNotPresent
          env:
            - name: BATCH_SIZE
              value: "100"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
