apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi-processor
  namespace: taxi-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taxi-processor
  template:
    metadata:
      labels:
        app: taxi-processor
    spec:
      containers:
        - name: taxi-processor
          image: taxi-processor:v1.01
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/taxidb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password