name: Build Check

on:
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build project
        run: ./gradlew build --no-daemon

  build-and-push-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push API image
      - name: Build and Push API
        run: |
          docker build -f src/api/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/taxi-api:v1.01 .
          docker push ${{ secrets.DOCKER_USERNAME }}/taxi-api:v1.01
      # Build and push Processor image
      - name: Build and Push Processor
        run: |
          docker build -f src/processor/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/taxi-processor:v1.01 .
          docker push ${{ secrets.DOCKER_USERNAME }}/taxi-processor:v1.01
      # Build and push Generator image
      - name: Build and Push Generator
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/taxi-generator:v1.01 src/data-generator
          docker push ${{ secrets.DOCKER_USERNAME }}/taxi-generator:v1.01